### ISSUE TITLE
Manage trustarc

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/Never-Consent#2]
https://www.trustarc.com/

Sample on https://www.twilio.com/

**Comment by MathRobin** [comment]
https://openclassrooms.com/fr/courses/235344-apprenez-a-programmer-en-python

**Comment by link2xt** [comment]
https://www.docker.com/ uses this too.

Processing shows percents going up slowly, but no network requests are actually made in the process.

Description here: https://cliqz.com/en/magazine/annoyed-by-cookie-consent-notices-there-is-a-method-behind-it

**Comment by MathRobin** [comment]
Many thanks for the article. It confirmed my doubts about the long loading was useless.

When will add the code for trustarc, after auto rejecting the consent, will force hide the modal.

If you're a developer, don't hesitate to participate, any contribution is welcomed.
