### ISSUE TITLE
Reduce permission level to the strictly minimum needed

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/Never-Consent#22]
Actually, it asks all permission. Too much large.

**Comment by MathRobin** [comment]
https://developer.chrome.com/extensions/declare_permissions

**Comment by MathRobin** [comment]
https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions

**Comment by MathRobin** [comment]
https://extensionworkshop.com/documentation/develop/request-the-right-permissions/#avoid-unnecessary-permissions

**Comment by ibrahimab** [comment]
Is this an issue that is still open and you need help with?

**Comment by MathRobin** [comment]
Yes please. I don't know how to reduce the permissions into the manifest. Sadly i'm not really good in english (hi french school system) and most of the docs are in english so i'm stuck on that point, can't go further and don't understand how to... If you have any idea or suggestion, don't hesitate you're welcome !

**Comment by ibrahimab** [comment]
I will work on this and produce a pull request!

**Comment by MathRobin** [comment]
A big big thanks for this message! I don't know how to do, so any help is welcome!
