### ISSUE TITLE
Manage AppConsent / SFBX

### ISSUE THREAD

**Issue by Shadok** [MathRobin/Never-Consent#28]
I found it on https://www.lyonmag.com

Loaded scripts :
```
<script defer src="https://cdn.appconsent.io/listener.1.2.0.js"></script>
<script defer src="https://cdn.appconsent.io/145/467/zZ1zvgiB/notice.js"></script>
```

It looks for window.frames.__cmpLocator then uses window.__cmp.

**Comment by MathRobin** [comment]
Oh great, many thanks ! Don't hesitate if you want to make a PR.

**Comment by Shadok** [comment]
I'd love to, but right now the consent modal seems to have been removed from the website.

**Comment by MathRobin** [comment]
Ah ah, will maybe have a look today

**Comment by MathRobin** [comment]
Done, will be pushed as soon as possible on marketplace

**Comment by Shadok** [comment]
They updated their code (found on lyonmag.com & lefigaro.fr).
I didn't manager to execute their denyAll function like you did before, neither made the elClick works.

window name seems to be webpackJsonpappconsent now.

Here's the relevant code i found :

* Check
`<div id="appconsent">`
or using window.webpackJsonpappconsent

* Réglages
```
<section class="sc-1nnqoje-1 kTblVO">
	<button class="hff8u9-0 wmGgB sc-1nnqoje-2 juvCHt button" type="button">
		<span class="sc-1aw7caq-0 hff8u9-1 dyUrjQ baseText">Réglages</span>
	</button>
</section>
```

* Tout refuser
`<a class="sc-10ckfh7-0 ibtwNj link">Tout Refuser</a>`

* Enregistrer
```
<button class="hff8u9-0 fDOcTE sc-1s6s8eg-0 kfXjGO button button--filled" type="button">
	<span class="sc-1aw7caq-0 hff8u9-1 gdgCV baseText">Enregistrer</span>
</button>
```
