### ISSUE TITLE
Find System behind

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/Never-Consent#29]
https://www.yumelise.fr/gratin-pommes-terre-mozzarella/

**Comment by milouse** [comment]
That's it https://www.createit.com/gdpr/

**Comment by milouse** [comment]
To kill it, it should be sufficient to create these two cookies:

- `ct-ultimate-gdpr-cookie-level` which contains `encodeURIComponent(btoa(1))`
- `ct-ultimate-gdpr-cookie` which contains `encodeURIComponent(btoa("{\"consent_declined\":false,\"consent_expire_time\":1623820521,\"consent_level\":1,\"consent_time\":1592284521}))"` (with correct time set)

I'm ready to try to open a PR on that one asap. Stay tuned

**Comment by MathRobin** [comment]
Hello ! Be welcomed ! If you want to open a PR, please feel confortable to do it ! And thanks for the help ?

Any idea if there is any other way to do it without creating the cookie ?

**Comment by MathRobin** [comment]
Done with https://github.com/MathRobin/Never-Consent/commit/98a151526365b5323e16a594e41c3b4f826d9489

Many thanks for your contribution ! Don't hesitate to open an issue or providing help^^
And don't hesitate to let a review on the store of your favorite browser store

**Comment by milouse** [comment]
Sorry to not have answered, I didn't have much time lately. I'll try your solution with pleasure :)

**Comment by MathRobin** [comment]
No problem
