### ISSUE TITLE
looping refresh on site downdetector.co.uk

### ISSUE THREAD

**Issue by zymurgic** [MathRobin/Never-Consent#30]
Reproduce steps:

Enable never-consent add-on in firefox with default settings
visit downdetector.co.uk

Ziff-Davis cookie consent form (with immense list of third-parties) keeps refreshing and looping.

**Comment by MathRobin** [comment]
Many thanks for this issue. Will investigate. Don't hesitate, if you want, to open new issues or pull request. Many thanks again !

**Comment by MathRobin** [comment]
Fixed here https://github.com/MathRobin/Never-Consent/commit/4a16ff4a2805579710ce9072aacf86e32e6ebd13

**Comment by jmoupah** [comment]
Hello,

same thing here with V1.10.0 on Firefox 83.0 / Windows 10 : https://www.fip.fr/groove/hip-hop/avec-yesterday-loyle-carner-et-madlib-tapent-dans-le-mille-18546

PS : thanks for the add-on :)
