### ISSUE TITLE
Same error constantly repeating on dell.com

### ISSUE THREAD

**Issue by Marsup** [MathRobin/Never-Consent#32]
Going to https://dell.com seems to cause a constant flood of errors, it just never stops.
Here are a few of the same:
![image](https://user-images.githubusercontent.com/796194/88040249-e51a2080-cb48-11ea-82bb-ec6694a583a5.png)

**Comment by MathRobin** [comment]
Duplicate https://github.com/MathRobin/Never-Consent/issues/30

**Comment by MathRobin** [comment]
Many thanks for reporting this bug ! And many thanks for using this extension !

**Comment by Marsup** [comment]
Oh sorry, I didn't see any refresh so I thought it was a different issue. Thanks for fixing it!

**Comment by MathRobin** [comment]
Nope, I was wrong, that was the same origin but not the same behavior. Fixed samed time at #30 

Don't hesitate to vote and rate for this extension on your browser store ! If you want to contribute again, mostly for a bug, don't hesitate too !
