### ISSUE TITLE
Filterlist

### ISSUE THREAD

**Issue by brian6932** [MathRobin/Never-Consent#39]
I was wondering if this extension could be made as a Filter List to be used in ad blockers like uBO, or does it need more permissions/features or something like that?

**Comment by MathRobin** [comment]
No idea. Never thought about this. Maybe.

It needs, for most of the platforms, complex actions, mostly in sequence. I don't know if adblockers can manage those kind of things.

Do you know if they can ?

**Comment by brian6932** [comment]
Not sure

**Comment by MathRobin** [comment]
Hello !

I found an uBlock list if you want https://github.com/MathRobin/Never-Consent#filterlist

Maybe it will answer to your problem

**Comment by brian6932** [comment]
oooh

**Comment by MathRobin** [comment]
your comment means that it's a solution valid for your question ? If yes, can i close this issue ?

**Comment by brian6932** [comment]
Eh kinda, I've used I don't care about cookies and that filterlist kinda expands on that, good enough though, the original point when I opened the thread might've been because I wanted to know whether or not you could refuse GPDR requests with a filterlist, but now I'm pretty sure you can't
