### ISSUE TITLE
Manage sipa cmp

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/Never-Consent#4]
https://github.com/Ouest-France/cmp
https://www.ouest-france.fr/leditiondusoir/data/63758/reader/reader.html

**Comment by jduval87** [comment]
A developper form Ouest-France mentionned in issue [#74](https://github.com/Ouest-France/cmp/issues/74) that this internal solution is getting retired in favour of Didomi.
I checked the main website and a few side-kick ones and could effectively not find sipa-cmp on any of them

**Comment by MathRobin** [comment]
Hello ! 

I subscribed to this issue to be notified about the answer of Ouest-France. For this info, and for all the PRs you made, a big big big big "thank you !!". I opened github and saw so much notifications, can't realize what happened !
You proved that open source is working !
Again: many thanks !
(will have a look soon to all your PRs)
