### ISSUE TITLE
Sirdata updated again

### ISSUE THREAD

**Issue by Shadok** [MathRobin/Never-Consent#43]
sirData updated their code again, but this time, all the button have the same class, and we need to rely on the children span to identify the right button to click.

- "Paramétrer vos choix" button
`<button class="sd-cmp-181cY"><span class="sd-cmp-2Pci8 sd-cmp-1BHAu sd-cmp-1jg0y" tabindex="-1">Paramétrer vos choix</span></button>`

- "Tout refuser" button
`<button class="sd-cmp-181cY"><span class="sd-cmp-2Pci8 sd-cmp-1xpje sd-cmp-1jg0y" tabindex="-1">Tout refuser</span></button>`

- "Enregistrer" button
`<button class="sd-cmp-181cY"><span class="sd-cmp-2Pci8 sd-cmp-1BHAu sd-cmp-1U8T_" tabindex="-1">Enregistrer</span></button>`

So it's not a simple class name updating.
Maybe if you add a parent bool parameter to the elClick function, so the given selector parameter would be used to locate the first button parent element ?

**Comment by MathRobin** [comment]
Hell, will see when i have time. Don't hesitate to make a PR if you want. Many thanks for the bug report !

**Comment by Shadok** [comment]
Pull request #44 created, i hope it works.

**Comment by MathRobin** [comment]
Merged, but sadly, they already updated it again...

**Comment by MathRobin** [comment]
Again: many thanks !
