### ISSUE TITLE
ManageConsent / SFBX has been updated

### ISSUE THREAD

**Issue by Shadok** [MathRobin/Never-Consent#46]
They updated their code (found on lyonmag.com & lefigaro.fr).
I didn't manager to execute their denyAll function like you did before, neither made the elClick works.

window name seems to be webpackJsonpappconsent now.

Here's the relevant code i found :

* Check
`<div id="appconsent">`
or using window.webpackJsonpappconsent

* Réglages
```
<section class="sc-1nnqoje-1 kTblVO">
	<button class="hff8u9-0 wmGgB sc-1nnqoje-2 juvCHt button" type="button">
		<span class="sc-1aw7caq-0 hff8u9-1 dyUrjQ baseText">Réglages</span>
	</button>
</section>
```

* Tout refuser
`<a class="sc-10ckfh7-0 ibtwNj link">Tout Refuser</a>`

* Enregistrer
```
<button class="hff8u9-0 fDOcTE sc-1s6s8eg-0 kfXjGO button button--filled" type="button">
	<span class="sc-1aw7caq-0 hff8u9-1 gdgCV baseText">Enregistrer</span>
</button>
```

**Comment by MathRobin** [comment]
They effectively removed appconsent js object which i used until now. I'm updating for the updated API

**Comment by Shadok** [comment]
It's will always be a game of hide and seek with this kind of companies ...

**Comment by MathRobin** [comment]
https://github.com/MathRobin/Never-Consent/commit/26a46b2ca2022421e0b16881260cf8f4427094a8

**Comment by MathRobin** [comment]
Published
