### ISSUE TITLE
Make extension available for Firefox under Android

### ISSUE THREAD

**Issue by beng7** [MathRobin/Never-Consent#48]
Hi
As Firefox now supports add-ons under android, can you make your extension available for android?
Thanks

**Comment by MathRobin** [comment]
Yes, I want it too. On Firefox marketplace, I declare it available for Firefox android but they changed extension engine, so there is just a few extensions available for real. I hope they will allow my extension to be available for Firefox android ASAP. Sadly I can't do more actually 😢

**Comment by PaulGrandperrin** [comment]
Hi, FYI, it is possible to install any addons on Firefox nightly: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
