### ISSUE TITLE
on / off option for each 

### ISSUE THREAD

**Issue by beng7** [MathRobin/Never-Consent#50]
Hi
Could you provide an Off / On option for each cookie type
e.g.
Google Maps                                                 Off / On
as i may choose to generally refuse all cookies but when it comes to Google Maps, I'm ok to allow these?
(youtube, facebook...)
Thanks

**Comment by MathRobin** [comment]
Hi, I understand why you ask this feature. But the goal of this extension is to always say no. If you want granularity, maybe you should choose another extension like consent o matic https://chrome.google.com/webstore/detail/consent-o-matic/mdjildafknihdffpkfmmpnpoiajfjnjd
