### ISSUE TITLE
Deny Borlabs Cookie

### ISSUE THREAD

**Issue by herrernst** [MathRobin/Never-Consent#52]
https://www.experto.de/

**Comment by MathRobin** [comment]
Hi ! Thanks for your contribution ! 

Some notes for the human who will do the dev:
- Every elements which can be unchecked is listed here : `borlabsCookieConfig.cookies`
- We can check status here for each one : `BorlabsCookie.checkCookieConsent('instagram')`
- Each can be desactivated with : BorlabsCookie.removeConsent('twitter')

Last one seems to doesn't work, will have a deeper look.

**Comment by mhellmeier** [comment]
Would be nice to see a Boarlabs Cookie integration soon.

[Borlabs Cookie](https://de.borlabs.io/borlabs-cookie/) is one of the most popular WordPress Cookie Consent plugins. It is customizable in some ways but the structure of the consent boxes are mostly the same. Shouldn't be that hard to integrate.

**Comment by MathRobin** [comment]
Hi,

Yeah I know, but I'm alone working on this extension on my free time (with a family, a job during the day, ...) so when will have time, will try to do. Don't hesitate to do a PR if you have the skills and the time.

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
