### ISSUE TITLE
Missing tags for releases

### ISSUE THREAD

**Issue by jan-kiszka** [MathRobin/Never-Consent#53]
Minor, but it would be nice to have the tags for the release pushed, corresponding to the packages on mozilla.org.

**Comment by MathRobin** [comment]
Not against this idea, but do you often install another version than the last version?
This extension really needs more tests and more CI/CD process, will probably add a tag logic for the next releases

**Comment by jan-kiszka** [comment]
It's primarily for the sake of consistency: I looked at the add-on page, 1.10.0. Then I looked here: 1.5.1. Source code no longer published? Obviously not. Also, it would easy to reproduce the published package.

I looked for this as your add-on was marked as "unchecked" by mozilla, so I preferred a look at the corresponding code first.

**Comment by MathRobin** [comment]
Oh ok, I understand. Will add it soon so

**Comment by MathRobin** [comment]
I've added some tags, and added a tag publish script in build script. Thanks for the enhancement idea

https://github.com/MathRobin/Never-Consent/tags
