### ISSUE TITLE
Looping refresh on fip

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/Never-Consent#54]
Hello,

same thing here with V1.10.0 on Firefox 83.0 / Windows 10 : https://www.fip.fr/groove/hip-hop/avec-yesterday-loyle-carner-et-madlib-tapent-dans-le-mille-18546

PS : thanks for the add-on :)

_Originally posted by @jmoupah in https://github.com/MathRobin/Never-Consent/issues/30#issuecomment-731227346_

**Comment by jduval87** [comment]
Hi

There is this parameter `onConsentChanged={() => location.reload()}` on ligne 21 of https://www.fip.fr/static/js/components/Didomi/Didomi.tsx which defeat this addon as Never-Consent forces a send of a "no-consent" whatever the consent state is.

So I guess a solution would be to check that state beforehand but I wasn't able to find a relevant and accessible property in the didomi scope.

My (maybe) dummy workaround would thus be to check the didomi banner in the DOM.
Something like : `!document.getElementById('didomi-host').attributes.getNamedItem('aria-hidden').value`

**Comment by MathRobin** [comment]
Wow many thanks for this contribution! I didn't had time to check this, so again : many thanks!

Sometimes a dummy workaround is the best way to address something. Mostly when it's for something which can be setup one time in browser. So don't care, a dummy solution is a solution

**Comment by jduval87** [comment]
It turned out that it was more dummy than a solution.
After more investigations I ended up with #56 
Feel free to adjust/refactor.

**Comment by MathRobin** [comment]
Merged, many thanks.

Released in 1.13.0, still waiting approval from Chrome / Firefox

**Comment by jmoupah** [comment]
I still have the issue on fip.fr after updating to 1.13.0 :( 
But not on https://www.didomi.io (but didn't tested before unforunatly)

**Comment by MathRobin** [comment]
Still waiting for the approval of Chrome. 1.13 version is already available on Firefox. What's your browser ?

**Comment by MathRobin** [comment]
I lied, it's now published on Chrome too. Can you give me more information to understand what happens ?

If don't want to expose private data in public, you can send me more details here mthrobin at "google mail well knwon domain"

**Comment by jmoupah** [comment]
Firefox.
I tried disabling others extensions, not better.

**Comment by jduval87** [comment]
I thinks there has been a problem with the release.
I installed the extension on another pc to get a fresh "clean" state and I have found the main script unmodified.

**Comment by MathRobin** [comment]
Maybe the build failed, will try a new deployment today

**Comment by MathRobin** [comment]
I confirmed that the package was not really updated, i sent the new version again, with a release 1.13.1. Sorry for the annoyance

**Comment by MathRobin** [comment]
It's already available on firefox. Can you test please ?

**Comment by jmoupah** [comment]
Great ! Thanx.

I can consulte one of my favorite radio website again,
you can try it, it's Jeff Bezos best radio also :) https://twitter.com/jack/status/907608254091599876
