### ISSUE TITLE
Manage Sibbo

### ISSUE THREAD

**Issue by waltermelow** [MathRobin/Never-Consent#55]
Fist, impressive project, congratulations!

Manage "Sibbo"

Example: `https://www.eldiario.es`

Detect: `window.SibboCMP`

![image](https://user-images.githubusercontent.com/196580/100554441-f3194400-3294-11eb-993f-895d20fc6332.png)

**Comment by MathRobin** [comment]
Due to great work of https://github.com/jduval87, this issue is now closed. Thank you !

**Comment by MathRobin** [comment]
Available on Firefox now
