### ISSUE TITLE
Add on/off button

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/Never-Consent#68]
hello,

Some website functionnality sometime need a consent.
I see some website using recaptcha on the loggin page, with an RGPD consent needed to do it but not classified as "nessesary" (because unlogged content dont need?? i think). 

Do you think that could be a good idea to add this when we click on "never-consent" icon on the toolbar ?

Regards

_Originally posted by @adrien-ber in https://github.com/MathRobin/Never-Consent/discussions/67_

**Comment by sorryusernameisalreadytaken** [comment]
I think this could be really useful. Perhaps the hand-icon could be paint in green if consent would affected the site, black if not supported the consent provider and red if disabled by the user.

**Comment by MathRobin** [comment]
Yes, i agree, i have an idea similar to this. Sadly, for the moment, I don't have time to work on this extension. Maybe in some months. Or maybe if somebody have time to do a PR
