### ISSUE TITLE
Manage Sourcepoint

### ISSUE THREAD

**Issue by dgreenhouse1** [MathRobin/Never-Consent#69]
https://www.sourcepoint.com/

CMP is up and running on their own site or on https://www.welt.de/ for testing.

**Comment by MathRobin** [comment]
Many thanks for your feature request

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
