### ISSUE TITLE
Make extension available for Pale Moon ?

### ISSUE THREAD

**Issue by lambic12** [MathRobin/Never-Consent#75]
Hello, this is a great extension, wish it would be available for Pale Moon !

**Comment by MathRobin** [comment]
Hi,

I didn't knew the existence of Pale Moon before reading this issue. Honestly, I don't have the time I would like to have to maintain this extension for main browsers (chromium-like + firefox) so I will not add any other browsers by myself for the moment.

If you want to make a PR, don't hesitate, you're welcome !
