### ISSUE TITLE
Feature request: Notification blip

### ISSUE THREAD

**Issue by Siccity** [MathRobin/Never-Consent#76]
Hello. I'm having a hard time determining the effectiveness of the extension. Would be nice with a little blip on the icon, or a log, or anything that can tell me if the extension actually worked. Because I am still seeing GDPR notices regularly.

**Comment by MathRobin** [comment]
Yes, you're true, I hope to have time to work on v2 version. Will have too an on/off button like on every good adblocker and a notification on icon.
I just need time to be able to work on it...

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
