### ISSUE TITLE
Manage Usercentrics

### ISSUE THREAD

**Issue by mhellmeier** [MathRobin/Never-Consent#80]
Another popular Consent Manager that isn't currently handeled is usercentrics:

https://usercentrics.com/

**Comment by MathRobin** [comment]
Oh great thank you, didn't knew this one. As tell in my answer to your other message, don't have time now to work on this extension. Don't hesitate to make a PR if you have time and skills (and if you want of course).

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
