### ISSUE TITLE
the extension break scrollbar on some site

### ISSUE THREAD

**Issue by fatpat** [MathRobin/Never-Consent#81]
With the extension, some site have no scroll bar. But when the extension is disabled, the scroll bar is back again and the website works correctly.

Here is a website with which I got the problem: https://www.service-public.fr/particuliers/vosdroits/F35249 :mask:

**Comment by MathRobin** [comment]
Hell... will have a look soon.

Many thanks for this bug report !

**Comment by MathRobin** [comment]
Fixed, waiting for deployment from Mozilla & Google. Again, many thanks for your bug report !

**Comment by MathRobin** [comment]
Now available on any chromium-like browsers and Firefox of course !
