### ISSUE TITLE
Qastk

### ISSUE THREAD

**Issue by Jfmblinux** [MathRobin/Never-Consent#82]
Bonjour,

Je ne sais pas si je suis au bon endroit, mais j'ai un autre site qui demande des consentements sans possibilité de choix : https://qastack.fr/
Et merci beaucoup pour la correction service-public.fr :blush: :pray: 
![Screenshot_20210330_134243](https://user-images.githubusercontent.com/54814723/112983351-e121b200-915d-11eb-9eb3-1c23e8d88734.png)

**Comment by MathRobin** [comment]
# En français
(english version will follow)

Ils se prendront des plaintes à la CNIL rapidement. Dès le 1er avril, on doit pouvoir refuser aussi facilement qu'accepter. C'est triste de devoir en arriver là mais tant pis pour eux.

Je vais voir si je peux m'en occuper prochainement, merci pour ce partage et n'hésite pas à en ouvrir d'autres. Ou même à faire des PRs si t'es chaud.

Et de rien pour service-public.fr, c'était effectivement très embêtant, ça m'a valu ma première "mauvaise note" sur le store de Firefox, un peu les boules mais c'est la vie.

# English version

This website doesn't respect the law, they will get some legal proceedings after the first of April 2021, when not providing an easy way to reject will become illegal in France. It's sad, but that's the law we were asking for.

Thank you for this report, don't hesitate to open more and more. And to contribute if you want / have time / have skills.

For service-public, you're welcome !
