### ISSUE TITLE
Blocking the cookie banner element often gives you less cookies than rejecting them.

### ISSUE THREAD

**Issue by jtagcat** [MathRobin/Never-Consent#83]
Looking at the code, it's more rejecting consent than never consenting.

I've experienced, that blocking cookie banners with uBlock doesn't plant more cookies. Functional cookies are planted anyway — functionality isn't lost.

This is more of an informational issue of somewhat miscommunication,, and for your interests.

**Comment by MathRobin** [comment]
Yeah, you're true, that's why in the first lines of the README file, i've added this parapgraph:

> **/!\ IMPORTANT:** This extension completes uBlock, AdBlock & co, they don't serve the same objectives. We promote usage of adblockers in completion. Never-Consent will (try to) reject consent as possible, it will not block ads, it will not be able block all cookies if sites doesn't care whether you / never-consent said nope.

https://github.com/MathRobin/Never-Consent/blob/master/README.md
