### ISSUE TITLE
Youtube Cookie banner should be supported

### ISSUE THREAD

**Issue by adeorato** [MathRobin/Never-Consent#86]
When I open Youtube I get this cookie banner in the beginning.
![grafik](https://user-images.githubusercontent.com/20139218/115140037-7addd000-a035-11eb-8f50-2cf2a5c2d411.png)
Is it possible to handle this cookie banner?

**Comment by jtagcat** [comment]
It's not YouTube. It's Google, consent.google.com.

**Comment by adeorato** [comment]
> 
> 
> It's not YouTube. It's Google, consent.google.com.

You are wrong:
![grafik](https://user-images.githubusercontent.com/20139218/115157106-b903df80-a087-11eb-8689-e9fb1e048071.png)

**Comment by jtagcat** [comment]
Right, now they effectively consent.youtube.com CNAME consent.google.com. It started with consent.google.com, and is more used than consent.youtube.com. Same thing anyway.

**Comment by MathRobin** [comment]
It's probably the same platform and will probably need the same solution. Thank you for having created (is that good english ? not sure) this issue! Don't hesitate to report other sites with that kind of problem and to make a PR if you want, if you can, and of course if you have the time for. Many thanks again !

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
