### ISSUE TITLE
Not working on Firefox 90

### ISSUE THREAD

**Issue by damienleger** [MathRobin/Never-Consent#89]
Hello,

I'm on Firefox developer edition, currently on version 90.0b6 and the extension doesn't seem to work. I see consent popup everytime ☹️

**Comment by MathRobin** [comment]
do you know on which platform ? all ? which of them ?

**Comment by damienleger** [comment]
On Windows. I tried another extension (https://addons.mozilla.org/fr/firefox/addon/consent-manager/) same happen.

**Comment by MathRobin** [comment]
Excuse me, I was not as clear as wanted.

Do you know with which consent platform ? Quantcast ? didomi ? tarteaucitron ? osano ? ... All of them ?
You can find a non-exhaustive list here https://github.com/MathRobin/Never-Consent#test

At least can you provide a quick list of sites where you met the problem ?

**Comment by damienleger** [comment]
OK got it 🙂 I've just clean my history to have the consent popup back. So far I have

one trust:
- https://www.disneyplus.com/
- https://www.netflix.com/

I will note them from now on and update the ticket.

**Comment by damienleger** [comment]
In addition I've tried the URLs on the link you gave me. It doesn't work for:

crownpeak / https://www.crownpeak.com/
osano / https://www.osano.com/
onetrust / https://www.lepoint.fr/
sirdata / https://sirdata.com/

**Comment by MathRobin** [comment]
OK, we can say that it's a big problem... Will try soon to understand what happens. I hope to have the same problems on Firefox 90 for Linux (don't have any windows / mac at home)

**Comment by damienleger** [comment]
Hello, another website where I have popup:

- axeptio / https://hcr-emploi.fr/
- axeptio / https://www.welcometothejungle.com/
- verizon media / https://consent.yahoo.com/
- ziff davis / https://www.speedtest.net/
- onetrust / https://aiven.io/

Also these ones, but I'm not sure about the consent platform:

- https://store.steampowered.com/ 
- https://circleci.com/ 
- https://www.reddit.com/ 
- https://www.paypal.com/ 
- https://www.facebook.com/ 
- https://www.betaseries.com/
- https://www.canalplus.com/
- https://www.journaldugeek.com/ 
- https://www.playstation.com/

**Comment by AlfredJKwack** [comment]
Hi,

Tried a sample of the URL's provided (see below) using NC v1.15.3 with FF 92.0.1 on MacOS 10.15.7 and did not encounter any issue. 

@damienleger could you confirm this is still an issue for you on Windows?

Sites checked:
- axeptio / https://hcr-emploi.fr/
- onetrust / https://aiven.io/
- ziff davis / https://www.speedtest.net/
- onetrust / https://www.lepoint.fr/
- crownpeak / https://www.crownpeak.com/

**Comment by AlfredJKwack** [comment]
@MathRobin that would be quite unfortunate. Never-Consent is the second most used plugin when looking at "consent" or "gdpr" as searches across the Mozilla store. There is definitely a space for this tool to exist in. The only other one that I can think of which I believe does things cleanly - as in actually denying cookies as opposed to just hiding the popup - would be Consent-O-Matic. If you do decide to archive this project, would you express your views on which other add-ons people could migrate to and how they differ from Never-Consent?
Thanks for the work and effort so far. It is truly appreciated.

**Comment by MathRobin** [comment]
It's an idea. I hope for a fork a day

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
