### ISSUE TITLE
Crédit Mutuel

### ISSUE THREAD

**Issue by Jfmblinux** [MathRobin/Never-Consent#90]
Bonjour,

Il y a aussi le https://www.creditmutuel.fr/ qui utilise et/ou passe par e-i.com pour le consentement.

**Comment by MathRobin** [comment]
Merci pour ce retour, je vais essayer de trouver le temps de développer de nouvelles choses sur cette extension prochainement. N'hésite pas à m'en envoyer d'autres

**Comment by MathRobin** [comment]
Malheureusement, je n'ai plus le temps de maintenir ce repo et donc l'extension. J'ai décidé d'archiver ce projet et de retirer l'extension des repos. Coeur sur vous :heart:
