### ISSUE TITLE
SirData broken

### ISSUE THREAD

**Issue by lemoustachiste** [MathRobin/Never-Consent#91]
Hi,

I can still see the SirData prompt, on both https://www.futura-sciences.com/ and https://www.sofoot.com/ for instance.
I looked at the code and it looks like the "Do not accept" button has the following class `. sd-cmp-1pO44`. Maybe that's a more reliable target. It's only 2 cases and that class seems auto generated, so not sure how reliable the fix would be?

**Comment by MathRobin** [comment]
They probably just have changed of version. Will have a look as soon as possible. Thanks !

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
