### ISSUE TITLE
seloger.com uses didomi

### ISSUE THREAD

**Issue by AlfredJKwack** [MathRobin/Never-Consent#94]
Hi,

There's an opportunity to refactor the code since it appears that seloger.com uses Didomi.

We can remove: 
https://github.com/MathRobin/Never-Consent/blob/ad7b22156093c4c3b19be594a60779a605ff2098/src/nc.js#L263-L280

How to validate (without Never-Consent turned on):
- Reset your browser history, caches etc.
- Visit [seloger.com](https://www.seloger.com/)
- open a console and run the check for Didomi. `if (!!window.Didomi && !!window.didomiOnReady) {console.log('Didomi');} >> Didomi`

Validated on Chrome and Safari on MacOs
<img width="1498" alt="Screenshot 2021-10-10 at 12 32 24" src="https://user-images.githubusercontent.com/557102/136691985-2a3a0c2b-8b50-4f9a-858b-8cc9b887ce3c.png">
.

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
