### ISSUE TITLE
Console logs are always present

### ISSUE THREAD

**Issue by Maks-s** [MathRobin/Never-Consent#95]
Seeing logs by Never-Consent each time I open the dev tools on any website is really annoying, e.g. on Github :

![image](https://user-images.githubusercontent.com/26678512/136799112-e1549460-e46e-4334-847d-c847a6e9815a.png)

**Comment by MathRobin** [comment]
Sadly I haven't time anymore to maintain. I decided to remove this extension from stores and archieve this repo. Many thanks to having try to help me. Many thanks again :heart:
